Update patch set 9
Patch Set 9:

> Hi Paul,
 > 
 > "Make lint" is failing.   One of the errors is "common/core/northbound/grpc/default_api_handler.go:253:82:
 > undefined: voltha.EventFilter" . Can you take a look?
 > 
 > Thanks
 > Khen

Hi Khen, As the proto changes got merged and the repo version is updated in go.mod, this error should not come. I am waiting for the changes in voltha-lib-go to get merged so that I can update the version in the go.mod

Patch-set: 9
Label: Code-Review=0