Update patch set 5
Patch Set 5:

> The only issue we cant help are how ubuntu tags its images:
 > 
 > ERROR: Parent 'ubuntu:trusty' is NOT using an specific version

Using 'ubuntu:14.04' instead of 'ubuntu:trusty' would probably solve this.

Patch-set: 5
Reviewer: Gerrit User 1000107 <1000107@2a2bfe1b-c5c2-48ed-9ac8-16438ab24388>
Label: Verified=0