Update patch set 8
Patch Set 8:

> Build Failed
 > 
 > https://jenkins.opencord.org/job/verify_voltha-go_unit-test-lint/246/
 > : FAILURE
 > 
 > https://jenkins.opencord.org/job/verify_voltha-go_unit-test-tests/249/
 > : FAILURE
 > 
 > https://jenkins.opencord.org/job/verify_voltha-go_licensed/512/ :
 > SUCCESS
 > 
 > https://jenkins.opencord.org/job/verify_voltha-go_tag-collision/197/
 > : SUCCESS
 > 
 > https://jenkins.opencord.org/job/verify-documentation/1917/ :
 > SUCCESS

Due to "dep ensure -update" k8s third party library got updated to latest. It would be great if someone who familiar with can fix below error 

9:36:04 # github.com/opencord/voltha-go/vendor/k8s.io/client-go/rest
19:36:04 vendor/k8s.io/client-go/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
19:36:04 	have (*versioned.Decoder)
19:36:04 	want (watch.Decoder, watch.Reporter)
19:36:29 Makefile:209: recipe for target 'lint-sanity' failed

Patch-set: 8